// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tswyarlwpovuhusflwqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzd3lhcmx3cG92dWh1c2Zsd3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTc3NDgsImV4cCI6MjA2NDQzMzc0OH0.kyEmVL9tAxa9ebApMoIwacu_Le7cEhOTwKV9JIZI3cQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);